vich_uploader:
    db_driver: orm

    mappings:
        jeuxvideo:
            uri_prefix: /images/jeuxvideo
            upload_destination: '%kernel.project_dir%/public/images/jeuxvideo'

            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true